apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-homework-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus-homework-service
  template:
    metadata:
      labels:
        app: otus-homework-service
    spec:
        containers:
        - name: otus-homework-service
          image: mrphelko/otususersapp:20230810154030
          ports:
            - name: web
              containerPort: 8000
          volumeMounts:
          - name: appsettings-volume
            mountPath: /app/configs
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db_password
        volumes:
        - name: appsettings-volume
          configMap:
            name: appsettings
            