apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otus-homework-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  #annotations:
    #kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: otus-homework-service
            port:
              number: 9000