apiVersion: v1
kind: Service
metadata:
  name: otus-homework-service
  labels:
    app: otus-homework-service
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: web
  selector:
    app: otus-homework-service
  type: NodePort